# Generated by Django 3.2.9 on 2021-12-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stack_overflow_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
