# Generated by Django 3.2.9 on 2021-12-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stack_overflow_app1', '0002_auto_20211207_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_comments',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
