# Generated by Django 3.2.9 on 2021-12-08 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stack_overflow_app1', '0003_community_comments_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='community_comments',
            name='for_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Stack_overflow_app1.question'),
        ),
    ]
